title: SiJie Liu's Homepage
page-top-title: SiJie Liu
top-section-bg-text: Transportation Engineering  
home-subtitle: "SiJie Liu&ensp;|&ensp; Ph.D. Student"
home-subtitle-2: "Department of Civil and Environmental Engineering, Old Dominion University"

copyright-text: '&copy; Sijie Liu 2023-2025. All Rights Reserved.'
